"""
Vector storage and retrieval service using ChromaDB
ChromaDB handles embedding generation automatically with all-MiniLM-L6-v2
"""
import logging
from typing import List, Dict, Optional
from app.database.chroma_client import get_product_collection
from app.services.document_processor import DocumentProcessor
from app.schemas.product import ContentSection

logger = logging.getLogger(__name__)


class VectorService:
    """
    Manage vector storage and retrieval in ChromaDB
    ChromaDB auto-generates embeddings when adding documents
    """

    def __init__(self):
        """Initialize VectorService with ChromaDB collection"""
        self.collection = get_product_collection()
        self.document_processor = DocumentProcessor()

    async def add_product_sections(
        self,
        product_id: str,
        user_id: str,
        sections: List[ContentSection]
    ) -> Dict[str, int]:
        """
        Add custom product content sections to ChromaDB
        Chunks each section and stores with embeddings (auto-generated)

        Args:
            product_id: Product UUID
            user_id: User UUID
            sections: List of ContentSection objects

        Returns:
            {
                "sections_processed": 3,
                "total_chunks": 15
            }
        """
        if not sections:
            logger.warning(f"No sections provided for product {product_id}")
            return {"sections_processed": 0, "total_chunks": 0}

        all_ids = []
        all_documents = []
        all_metadatas = []
        total_chunks = 0

        for section_idx, section in enumerate(sections):
            # Chunk the section content
            chunks = self.document_processor.chunk_content_section(
                section_name=section.name,
                section_content=section.content
            )

            for chunk in chunks:
                # Create unique ID
                chunk_id = f"{product_id}_section_{section_idx}_chunk_{chunk['chunk_index']}"

                # Prepare metadata
                metadata = {
                    "product_id": product_id,
                    "user_id": user_id,
                    "source_type": "section",
                    "source_id": f"section_{section_idx}",
                    "section_name": section.name,
                    "chunk_index": chunk['chunk_index'],
                    "chunk_total": len(chunks),
                    "token_count": chunk['token_count']
                }

                all_ids.append(chunk_id)
                all_documents.append(chunk['text'])
                all_metadatas.append(metadata)
                total_chunks += 1

        # Add all to ChromaDB (embeddings auto-generated)
        if all_ids:
            self.collection.add(
                ids=all_ids,
                documents=all_documents,
                metadatas=all_metadatas
            )
            logger.info(
                f"Added {total_chunks} chunks from {len(sections)} sections "
                f"for product {product_id}"
            )

        return {
            "sections_processed": len(sections),
            "total_chunks": total_chunks
        }

    async def add_document_chunks(
        self,
        product_id: str,
        user_id: str,
        document_id: str,
        document_name: str,
        chunks: List[Dict]
    ) -> int:
        """
        Add document chunks to ChromaDB
        Embeddings are auto-generated by ChromaDB

        Args:
            product_id: Product UUID
            user_id: User UUID
            document_id: Document UUID
            document_name: Original filename
            chunks: List of chunk dicts from DocumentProcessor

        Returns:
            Number of chunks added
        """
        if not chunks:
            logger.warning(f"No chunks provided for document {document_id}")
            return 0

        ids = []
        documents = []
        metadatas = []

        for chunk in chunks:
            # Create unique ID
            chunk_id = f"{product_id}_doc_{document_id}_chunk_{chunk['chunk_index']}"

            # Prepare metadata
            metadata = {
                "product_id": product_id,
                "user_id": user_id,
                "source_type": "document",
                "source_id": document_id,
                "document_name": document_name,
                "chunk_index": chunk['chunk_index'],
                "chunk_total": len(chunks),
                "token_count": chunk['token_count']
            }

            ids.append(chunk_id)
            documents.append(chunk['text'])
            metadatas.append(metadata)

        # Add to ChromaDB
        self.collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas
        )

        logger.info(
            f"Added {len(chunks)} chunks from document '{document_name}' "
            f"(product {product_id})"
        )

        return len(chunks)

    async def query_product_knowledge(
        self,
        product_id: str,
        query: str,
        top_k: int = 5
    ) -> List[Dict]:
        """
        Query ChromaDB for relevant product knowledge
        Query embedding is auto-generated by ChromaDB

        Args:
            product_id: Product UUID to filter by
            query: Natural language query
            top_k: Number of results to return

        Returns:
            List of results:
            [
                {
                    "text": "chunk text...",
                    "distance": 0.32,  # Lower = more similar
                    "source_type": "section" | "document",
                    "source_name": "Pricing" | "Brief.pdf",
                    "chunk_index": "2/5",
                    "metadata": {...}
                },
                ...
            ]
        """
        try:
            # Query ChromaDB with product_id filter
            results = self.collection.query(
                query_texts=[query],
                n_results=top_k,
                where={"product_id": product_id}
            )

            # Format results
            formatted_results = []

            if results['ids'] and len(results['ids'][0]) > 0:
                for i in range(len(results['ids'][0])):
                    metadata = results['metadatas'][0][i]
                    distance = results['distances'][0][i]
                    text = results['documents'][0][i]

                    # Determine source name
                    if metadata['source_type'] == 'section':
                        source_name = metadata.get('section_name', 'Unknown Section')
                    else:
                        source_name = metadata.get('document_name', 'Unknown Document')

                    formatted_results.append({
                        "text": text,
                        "distance": distance,
                        "similarity": 1 - distance,  # Convert distance to similarity score
                        "source_type": metadata['source_type'],
                        "source_name": source_name,
                        "chunk_index": f"{metadata['chunk_index']}/{metadata['chunk_total']}",
                        "metadata": metadata
                    })

            logger.info(
                f"Query for product {product_id} returned {len(formatted_results)} results"
            )

            return formatted_results

        except Exception as e:
            logger.error(f"Query failed for product {product_id}: {str(e)}")
            return []

    def delete_product_vectors(self, product_id: str) -> int:
        """
        Delete all vectors for a product

        Args:
            product_id: Product UUID

        Returns:
            Number of vectors deleted (estimated)
        """
        try:
            # Get count before deletion
            before_count = self.collection.count()

            # Delete all vectors with this product_id
            self.collection.delete(
                where={"product_id": product_id}
            )

            after_count = self.collection.count()
            deleted = before_count - after_count

            logger.info(f"Deleted {deleted} vectors for product {product_id}")
            return deleted

        except Exception as e:
            logger.error(f"Failed to delete vectors for product {product_id}: {str(e)}")
            return 0

    def delete_document_vectors(self, document_id: str) -> int:
        """
        Delete all vectors for a specific document

        Args:
            document_id: Document UUID

        Returns:
            Number of vectors deleted (estimated)
        """
        try:
            before_count = self.collection.count()

            # Delete vectors for this document
            # ChromaDB requires $and operator for multiple conditions
            self.collection.delete(
                where={
                    "$and": [
                        {"source_type": "document"},
                        {"source_id": document_id}
                    ]
                }
            )

            after_count = self.collection.count()
            deleted = before_count - after_count

            logger.info(f"Deleted {deleted} vectors for document {document_id}")
            return deleted

        except Exception as e:
            logger.error(f"Failed to delete vectors for document {document_id}: {str(e)}")
            return 0

    def delete_section_vectors(self, product_id: str) -> int:
        """
        Delete all section vectors for a product (keep document vectors)

        Args:
            product_id: Product UUID

        Returns:
            Number of vectors deleted (estimated)
        """
        try:
            before_count = self.collection.count()

            # Delete only section vectors for this product
            # ChromaDB requires $and operator for multiple conditions
            self.collection.delete(
                where={
                    "$and": [
                        {"product_id": product_id},
                        {"source_type": "section"}
                    ]
                }
            )

            after_count = self.collection.count()
            deleted = before_count - after_count

            logger.info(f"Deleted {deleted} section vectors for product {product_id}")
            return deleted

        except Exception as e:
            logger.error(f"Failed to delete section vectors for product {product_id}: {str(e)}")
            return 0

    def get_collection_stats(self) -> Dict:
        """
        Get statistics about the vector collection

        Returns:
            {
                "total_vectors": 1234,
                "collection_name": "product_knowledge"
            }
        """
        return {
            "total_vectors": self.collection.count(),
            "collection_name": self.collection.name
        }
